# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQTT-service' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  project 'MQTT-service.xcodeproj'
  platform :ios, '8.0'
  pod 'CocoaMQTT'
  # Pods for MQTT-service

end
